application: email2httppost
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/mail/.+
  script: email2httppost.app

inbound_services:
- mail

env_variables:
  DESTINATION_URL: 'http://where.to.send.it''


